In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [12]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT f.name, SUM(
        CASE WHEN memid = 0 THEN b.slots * f.guestcost
        ELSE b.slots * f.membercost END
                      ) AS revenue
    FROM Bookings AS b
    INNER JOIN Facilities AS f
        ON b.facid = f.facid
    GROUP BY f.name
    HAVING revenue < 1000
    ORDER BY revenue
    """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q10. Answers")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q10. Answers
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [10]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT m.firstname AS memberfirstname, m.surname AS membersurname, rec.firstname AS recfirstname, rec.surname AS recsurname
    FROM Members AS m
    LEFT JOIN Members AS rec
        ON m.recommendedby = rec.memid
    ORDER BY m.surname, m.firstname
    """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q11. Answers")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q11. Answers
('Florence', 'Bader', 'Ponder', 'Stibbons')
('Anne', 'Baker', 'Ponder', 'Stibbons')
('Timothy', 'Baker', 'Jemima', 'Farrell')
('Tim', 'Boothe', 'Tim', 'Rownam')
('Gerald', 'Butters', 'Darren', 'Smith')
('Joan', 'Coplin', 'Timothy', 'Baker')
('Erica', 'Crumpet', 'Tracy', 'Smith')
('Nancy', 'Dare', 'Janice', 'Joplette')
('David', 'Farrell', None, None)
('Jemima', 'Farrell', None, None)
('GUEST', 'GUEST', None, None)
('Matthew', 'Genting', 'Gerald', 'Butters')
('John', 'Hunt', 'Millicent', 'Purview')
('David', 'Jones', 'Janice', 'Joplette')
('Douglas', 'Jones', 'David', 'Jones')
('Janice', 'Joplette', 'Darren', 'Smith')
('Anna', 'Mackenzie', 'Darren', 'Smith')
('Charles', 'Owen', 'Darren', 'Smith')
('David', 'Pinker', 'Jemima', 'Farrell')
('Millicent', 'Purview', 'Tracy', 'Smith')
('Tim', 'Rownam', None, None)
('Henrietta', 'Rumney', 'Matthew', 'Genting')
('Ramnaresh', 'Sarwin', 'Florence', 'Bader')
('Darren', 'Smith', None, None)
('Darren', 'Smith', None, None)
('Jack', 'Smith', 'Darren', 'Smith')
('Tracy', 'Smith', None, None)
('Ponder', 'Stibbons', 'Burton', 'Tracy')
('Burton', 'Tracy', None, None)
('Hyacinth', 'Tupperware', None, None)
('Henry', 'Worthington-Smyth', 'Tracy', 'Smith')

In [11]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT f.name,SUM(slots) AS memberstotalusage
    FROM Bookings AS b
    INNER JOIN Facilities AS f
        ON b.facid = f.facid
    WHERE memid > 0
    GROUP BY f.name
    """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q12. Answers")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q12. Answers
('Badminton Court', 1086)
('Massage Room 1', 884)
('Massage Room 2', 54)
('Pool Table', 856)
('Snooker Table', 860)
('Squash Court', 418)
('Table Tennis', 794)
('Tennis Court 1', 957)
('Tennis Court 2', 882)

In [22]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT f.name, strftime('%m', starttime) AS month, SUM(slots) AS memberstotalusage
    FROM Bookings AS b
    INNER JOIN Facilities AS f
        ON b.facid = f.facid
    WHERE memid > 0
    GROUP BY f.name, month
    """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q13. Answers")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q13. Answers
('Badminton Court', '07', 165)
('Badminton Court', '08', 414)
('Badminton Court', '09', 507)
('Massage Room 1', '07', 166)
('Massage Room 1', '08', 316)
('Massage Room 1', '09', 402)
('Massage Room 2', '07', 8)
('Massage Room 2', '08', 18)
('Massage Room 2', '09', 28)
('Pool Table', '07', 110)
('Pool Table', '08', 303)
('Pool Table', '09', 443)
('Snooker Table', '07', 140)
('Snooker Table', '08', 316)
('Snooker Table', '09', 404)
('Squash Court', '07', 50)
('Squash Court', '08', 184)
('Squash Court', '09', 184)
('Table Tennis', '07', 98)
('Table Tennis', '08', 296)
('Table Tennis', '09', 400)
('Tennis Court 1', '07', 201)
('Tennis Court 1', '08', 339)
('Tennis Court 1', '09', 417)
('Tennis Court 2', '07', 123)
('Tennis Court 2', '08', 345)
('Tennis Court 2', '09', 414)

In [23]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    With Booking20120914 AS (
        SELECT *
        FROM Bookings
        WHERE starttime >= '2012-09-14' AND starttime < '2012-09-15')
SELECT
    CONCAT(m.firstname," ",m.surname) AS memberfullname, f.name AS facility,
    CASE WHEN m.memid = 0 THEN b1.slots * f.guestcost
         ELSE b1.slots * f.membercost END AS cost
FROM Members AS m
    INNER JOIN Booking20120914 AS b1
            ON m.memid = b1.memid
    INNER JOIN Facilities AS f
            ON b1.facid = f.facid
WHERE (m.memid = 0 AND b1.slots * f.guestcost > 30) OR
      (m.memid <> 0 AND b1.slots * f.membercost > 30)
ORDER BY cost DESC
    """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q13. Answers")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q13. Answers

OperationalError: no such function: CONCAT